mqtt:
  enabled: true
  host: mqtt
cameras:
  patrol_camera:
    ffmpeg:
      inputs:
        - path: rtsp://CHANGE_ME
          roles: [detect, record]
    detect:
      width: 1280
      height: 720
    objects:
      track: [person, car, bicycle, motorcycle, dog, cat]
record:
  enabled: true
  retain:
    days: 1
  alerts:
    retain:
      days: 7
